[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "bellamoosh_erp"
version = "1.0.0"
description = "Custom ERP for Bellamoosh Lifestyle LLP — Fabric Export"
authors = [
    {name = "Bellamoosh Lifestyle LLP", email = "info@bellamoosh.com"}
]
dependencies = [
    "frappe",
    "pypika @ git+https://github.com/frappe/pypika@2c50e6142b2d61d2d243e466fdd5dc03b3d918f2",
    "gunicorn @ git+https://github.com/frappe/gunicorn@bb554053bb87218120d76ab6676af7015680e8b6"
]
requires-python = ">=3.8"

[tool.setuptools]
packages = ["bellamoosh_erp"]
include-package-data = true
zip-safe = false